If you want to fillout the form a checkout form within the browser you can find it in the following route
but the form is not working because it's not sending the data in the correct format and i'm not into the mood to fix it
http://localhost:3000/api

###

POST http://localhost:3000/api/checkout
Content-Type: application/json

{
  "order_cart": [
    {
      "name": "iphone x",
      "amount_cents": "2400000",
      "description": "iphone x 64GB",
      "quantity": "1"
    }
  ],
  "billing_data": {
    "apartment": "803",
    "email": "claudette09@exa.com",
    "floor": "42",
    "first_name": "Clifford",
    "street": "Ethan Land",
    "building": "8028",
    "phone_number": "+86(8)9135210487",
    "shipping_method": "PKG",
    "postal_code": "01898",
    "city": "Jaskolskiburgh",
    "country": "CR",
    "last_name": "Nicolas",
    "state": "Utah"
  },
  "amount_cents": "2400000"
}